#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/commands.h"

char* generate_cmake_template(const char *project_name) {
  char *template = malloc(2048);
  snprintf(template, 2048,
           "# Minimum CMake version\n"
           "cmake_minimum_required(VERSION 3.15)\n\n"
           "# Project definition\n"
           "project(%s\n"
           "    VERSION 1.0.0\n"
           "    DESCRIPTION \"A C project created with sbor\"\n"
           "    LANGUAGES C\n"
           ")\n\n"
           "# Set C standard\n"
           "set(CMAKE_C_STANDARD 17)\n"
           "set(CMAKE_C_STANDARD_REQUIRED ON)\n\n"
           "# Set default build type to Release if not specified\n"
           "if(NOT CMAKE_BUILD_TYPE)\n"
           "    set(CMAKE_BUILD_TYPE Release)\n"
           "endif()\n\n"
           "# Source files\n"
           "set(SOURCES\n"
           "    src/main.c\n"
           "    # Add more .c files here as needed\n"
           ")\n\n"
           "# Create executable\n"
           "add_executable(${PROJECT_NAME} ${SOURCES})\n\n"
           "# Include directories\n"
           "target_include_directories(${PROJECT_NAME} PRIVATE src)\n\n"
           "# Compiler flags\n"
           "target_compile_options(${PROJECT_NAME} PRIVATE\n"
           "    $<$<C_COMPILER_ID:GNU,Clang>:-Wall -Wextra -Wpedantic>\n"
           "    $<$<C_COMPILER_ID:MSVC>:/W4>\n"
           "    \n"
           "    $<$<CONFIG:Debug>:\n"
           "        $<$<C_COMPILER_ID:GNU,Clang>:-g -O0>\n"
           "        $<$<C_COMPILER_ID:MSVC>:/Od /Zi>\n"
           "    >\n"
           "    \n"
           "    $<$<CONFIG:Release>:\n"
           "        $<$<C_COMPILER_ID:GNU,Clang>:-O3 -DNDEBUG>\n"
           "        $<$<C_COMPILER_ID:MSVC>:/O2 /DNDEBUG>\n"
           "    >\n"
           ")\n\n"
           "message(STATUS \"Build type: ${CMAKE_BUILD_TYPE}\")\n"
           "message(STATUS \"C compiler: ${CMAKE_C_COMPILER}\")\n",
           project_name);
  return template;
}

char* generate_main_template(void) {
  char *template = malloc(512);
  snprintf(template, 512,
           "#include \"include.h\"\n\n"
           "int main(void) {\n"
           "    printf(\"Hello from sbor!\\n\");\n"
           "    printf(\"Project initialized successfully.\\n\");\n"
           "    return 0;\n"
           "}\n");
  return template;
}

char* generate_include_template(void) {
  char *template = malloc(300);
  snprintf(template, 300,
           "// Auto-generated by sbor - Managed header includes\n"
           "// Use 'sbor add <header>' to add system headers\n"
           "// Use 'sbor add <header> -c' to add custom headers\n\n"
           "// System headers\n"
           "#include <stdio.h>\n"
           "#include <stdlib.h>\n\n"
           "// Custom headers\n"
           "// Add your custom includes here\n");
  return template;
}

char* generate_readme_template(const char *project_name) {
  char *template = malloc(512);
  snprintf(template, 512, "# %s\n\n", project_name);
  return template;
}

char* generate_gitignore_template(void) {
  char *template = malloc(512);
  snprintf(template, 512,
           "# Build directories\n"
           "build/\n"
           "bin/\n"
           "obj/\n\n"
           "# Compiled binaries\n"
           "*.exe\n"
           "*.out\n"
           "*.app\n\n"
           "# Object files\n"
           "*.o\n"
           "*.obj\n\n"
           "# Debug files\n"
           "*.pdb\n"
           "*.ilk\n\n"
           "# CMake generated files\n"
           "CMakeCache.txt\n"
           "CMakeFiles/\n"
           "cmake_install.cmake\n"
           "Makefile\n"
           "*.cbp\n\n"
           "# IDE files\n"
           ".vscode/\n"
           ".idea/\n"
           "*.swp\n"
           "*.swo\n"
           "*~\n\n"
           "# OS files\n"
           ".DS_Store\n"
           "Thumbs.db\n");
  return template;
}

char* generate_config_template(const char *project_name) {
  char *template = malloc(512);
  snprintf(template, 512,
           "{\n"
           "    \"name\": \"%s\",\n"
           "    \"version\": \"1.0.0\",\n"
           "    \"c_standard\": \"c17\",\n"
           "    \"includes\": {\n"
           "        \"system\": [\"stdio.h\", \"stdlib.h\"],\n"
           "        \"custom\": []\n"
           "    },\n"
           "    \"build\": {\n"
           "        \"compiler\": \"gcc\",\n"
           "        \"flags\": [\"-Wall\", \"-Wextra\", \"-O2\"],\n"
           "        \"output_dir\": \"build\"\n"
           "    }\n"
           "    \"run\": {\n"
           "          \"quiet_mode\": false\n"
           "     }\n"
           "}\n",
           project_name);
  return template;
}
